# Generated by Django 4.1.1 on 2023-09-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Year One', 'YR1'), ('Year Two', 'YR2')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=100)),
                ('unit', models.IntegerField()),
                ('grade', models.IntegerField(choices=[('A', 5), ('B', 4), ('C', 3)])),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.year')),
            ],
        ),
    ]
