# Generated by Django 4.1.1 on 2023-09-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_cgpa_enrollment_student_delete_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='semester',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, choices=[('Harmattan', 'Harmattan'), ('Rain', 'Rain')], max_length=50, null=True),
        ),
    ]
