# Generated by Django 4.2.5 on 2023-09-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_enrollment_semester_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgpa',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(choices=[('Year One', 'YR1'), ('Year Two', 'YR2'), ('Year Three', 'YR3'), ('Year Four', 'YR4'), ('Year Five', 'YR5')], max_length=10),
        ),
    ]
